# Generated by Django 3.0 on 2020-01-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classif', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('reporter', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('classif', models.CharField(max_length=30)),
                ('learnmore', models.TextField()),
            ],
        ),
    ]
