# Generated by Django 3.0 on 2020-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('img_path', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
    ]
