# Generated by Django 3.0 on 2020-01-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200115_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='img_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
